argsDir: '{{CWD}}'
reportsDir: '{{CWD}}/reports'
plugins:
  hapi-password:
    password: '{{getEnv("AUTH_PASSWORD")}}'
    salt: '{{getEnv("AUTH_SALT")}}'
    isSecure: '{{getEnv("IS_SECURE", false)}}'
  hapi-method-scheduler:
    schedule: []
  hapi-method-loader:
    path: '{{LIBDIR}}/methods'
  hapi-route-loader:
    path: '{{LIBDIR}}/routes'
    _dependencies:
      'hapi-password'
  '{{LIBDIR}}/plugins/reporter.js':
    _dependencies:
      - 'hapi-method-scheduler'
      - 'hapi-method-loader'
  '{{LIBDIR}}/plugins/aws.js':
  hapi-transform-table:
  hapi-transform-csv:
