argsDir: '{{CWD}}'
reportsDir: '{{CWD}}/reports'
plugins:
  hapi-password:
    password: '{{envVars.hapiPassword.password}}'
    salt: '{{envVars.hapiPassword.salt}}'
    isSecure: '{{envVars.hapiPassword.isSecure}}'
  hapi-method-scheduler:
    schedule: []
  hapi-method-loader:
    path: '{{LIBDIR}}/methods'
  hapi-route-loader:
    path: '{{LIBDIR}}/routes'
    _dependencies:
      'hapi-password'
  '{{LIBDIR}}/plugins/reporter.js':
    _dependencies:
      - 'hapi-method-scheduler'
      - 'hapi-method-loader'
  '{{LIBDIR}}/plugins/aws.js':
  '{{LIBDIR}}/plugins/email.js':
    _dependencies:
      - 'hapi-method-scheduler'
      - 'hapi-method-loader'
    host: '{{envVars.email.host}}'
    port: '{{envVars.email.port}}'
    user: '{{envVars.email.user}}'
    password: '{{envVars.email.password}}'
  hapi-transform-table:
  hapi-transform-csv:
