argsDir: '{{CWD}}'
reportsDir: '{{CWD}}/reports'
plugins:
  hapi-password:
    _enabled: '{{envExists("AUTH_PASSWORD")}}'
    password: '{{getEnv("AUTH_PASSWORD", false)}}'
    salt: '{{getEnv("AUTH_SALT", false)}}'
  hapi-method-scheduler:
    schedule: []
  hapi-method-loader:
    path: '{{LIBDIR}}/methods'
  hapi-route-loader:
    path: '{{LIBDIR}}/routes'
  '{{LIBDIR}}/plugins/reporter.js':
    _dependencies:
      - 'hapi-method-scheduler'
      - 'hapi-method-loader'
  '{{LIBDIR}}/plugins/aws.js':
  hapi-transform-table:
  hapi-transform-csv:
