argsDir: '{{CWD}}'
reportsDir: '{{CWD}}/reports'
plugins:
  hapi-password:
   _enabled: '{{ENV.AUTH_PASSWORD !== undefined}}'
  hapi-method-scheduler:
    schedule: []
  hapi-method-loader:
    path: '{{LIBDIR}}/methods'
  hapi-route-loader:
    path: '{{LIBDIR}}/routes'
  '{{LIBDIR}}/plugins/reporter.js':
    _dependencies:
      - 'hapi-method-scheduler'
      - 'hapi-method-loader'
  '{{LIBDIR}}/plugins/aws.js':
  hapi-transform-table:
  hapi-transform-csv:
